### ISSUE TITLE
Classic SoD: World boss kills not recorded.

### ISSUE THREAD

**Issue by Painstormx** [juemrami/SavedInstances#16]
Just killed Azuregos, Kazzak and Onyxia and none of these seem to be picked up by the addon. Kazzak and Azuregos are instanced versions in SoD, so they probably have new ID's there.
EDIT: The onyxia kill actually showed up in the addon the next day for some reason.

**Comment by juemrami** [comment]
Do the instanced world bosses show up in the blizzard Raid Lockouts?

**Comment by Painstormx** [comment]
Well, I'm 90% sure they did show up, but obviously they are gone now :)
However, I also did MC and that definitely showed up in Blizzard Raid Lockouts, but not in SavedInstances.

**Comment by juemrami** [comment]
okay, ill see what i can do. 
The issue is i dont play SoD atm and these kinds of things require me to play the game to generate the data on my end to update the addon logic so that its parses the data correctly.

**Comment by Painstormx** [comment]
If there's anything I can help test, just let me know.
I don't raid a lot though.

**Comment by Painstormx** [comment]
I'm currently locked to MC if there's something you want me to test.
It does show up in the Raid Info tab, but the addon is not showing anything.

**Comment by juemrami** [comment]
Yo, ive been super distracted with other projects and looking for a job atm. So sorry im not able to super focus on the addon atm. That being said,

I know its past reset at this point but, next time you get saved run this script and post text (or screenshot if u dont have copy paste in chat) output for me.

```
/run for i = 1, GetNumSavedInstances() do DevTools_Dump({GetSavedInstanceInfo(i)}) end
```

I'll try to make some time this week to go over this. Ty for ur patience

**Comment by Painstormx** [comment]
![image](https://github.com/user-attachments/assets/7682ef6e-faa6-4876-976c-0e03ab70be2c)
Still nothing in addon.

**Comment by juemrami** [comment]
Okay i can see an issue right away. This helps getting MC tracked again. 
It has to do with the difficulty ID (`[4] = 226`), i only checked up to difficulty 215 before, this is a new one that was added for SoD. 

I know that theyre changing the size of bwl/zg to be flex in SoD, Im watching the PTR atm so ill see if they add in any more difficulty IDs

**Comment by juemrami** [comment]
The world boss outputs would help if you get a hold of em. Ill ask around to some friends that still play wow

**Comment by Painstormx** [comment]
MC actually has 3 difficulties in SoD: Heat 1/2/3.
The data shown is from a Heat 1 lock. So there might also be difficulty ID's 227 and 228.

**Comment by juemrami** [comment]
It looks like [226](https://wago.tools/db2/Difficulty?build=1.15.4.56419&sort[ID]=desc) is the max atm, still waiting on the next ptr build to see if theyre adding new ones for phase 5.

Ive pushed a new alpha version to check out
https://legacy.curseforge.com/wow/addons/savedinstances-classic/files/5687469

I dont think this fixes the world bosses but, MC should be there now. 
Also if you could lmk if the other bugs are still there, i pushed an alpha with fixes for those like a week ago.

**Comment by Painstormx** [comment]
MC and the other bugs fixed in latest build :)

**Comment by Believe82** [comment]
Sorry to barge in on your conversation but maybe I can help with more data. I raid a lot and can help also give you more data..
This is me saved for MC, ZG and the new Crystal Vale World bos: (running BWL on Monday and will add that too the mix)

![image](https://github.com/user-attachments/assets/2ce59a9a-9ea9-4bff-a069-dba2a71f5401)

And this is Lord Kazzak another World Boss:
![image](https://github.com/user-attachments/assets/f1634094-3135-439a-8aec-7002074e2052)

**Comment by juemrami** [comment]
> Sorry to barge in on your conversation

@Believe82 No please, this data is very welcome, thank you xD

**Comment by juemrami** [comment]
If you could test out the latest fix and lmk if its still missing stuff that would be dope
https://legacy.curseforge.com/wow/addons/savedinstances-classic/files/5765963

**Comment by Believe82** [comment]
![image](https://github.com/user-attachments/assets/18d91617-ca6f-4a0f-8b20-16978a917828)

Amazing work!

**Comment by juemrami** [comment]
Ty. Im interested to see if it picks up BWL correctly. If so ill push this build as `v0.1.7`

**Comment by Believe82** [comment]
![image](https://github.com/user-attachments/assets/8bfc9906-65d8-4ab3-a5d4-d5c0d0ac6d80)

Working as intended!!!
